name: Build Check and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenche le pipeline sur les commits dans la branche main
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  # Job d'analyse CodeQL
  codeql-analysis:
    name: Analyze Code with CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: true  # Arrête le job dès qu'une erreur est rencontrée
      #matrix:
        # Remplacez par les langages présents dans votre projet
       # language: [ 'python' ]  # Par exemple, spécifiez uniquement 'python'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Passez à v3 pour utiliser Node.js 16 ou 20

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3  # Passez à v3
        with:
          #languages: ${{ matrix.language }}  # Spécifiez les langages à analyser
          build-mode: none  # Utilisez build-mode au lieu de autobuild

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3  # Passez à v3
        with:
          category: security  # Catégorie d'analyse orientée sécurité
        continue-on-error: false  # Stoppe l'exécution du job si une vulnérabilité critique est détectée

  # Job de build et scan Docker, qui s'exécute seulement si le job codeql-analysis réussit
  build-and-scan:
    needs: codeql-analysis  # Dépend du job codeql-analysis
    runs-on: ubuntu-latest
    if: ${{ needs.codeql-analysis.result == 'success' }}  # S'exécute seulement si codeql-analysis a réussi
    
    steps:
      # Checkout du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Configuration de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construire l'image Docker
      - name: Build Docker image
        working-directory: ./function_image1
        run: |
          docker build -t ${{ secrets.MY_CONTAINER }}/day-function:latest .

      # Analyser l'image avec Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.MY_CONTAINER }}/day-function:latest
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          exit-code: 1

      # Pousser l'image Docker sur Docker Hub
      - name: Push Docker image
        if: success()  # Exécuter seulement si le scan Trivy réussit
        run: |
          docker push ${{ secrets.MY_CONTAINER }}/day-function:latest
