name: Build Check and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenche le pipeline sur les commits dans la branche main
  workflow_dispatch:  # Permet de déclencher manuellement le workflow
    inputs:
      file_to_analyze:
        description: 'Path of the Python file to analyze'
        required: true
        default: 'evaluate_work/test1.py'

jobs:
 # Job pour ajouter des evil packages à requirements.txt
  add-evil-packages:
    name: Add Evil PyPI Packages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Vérification du dépôt

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Add Evil PyPI Packages
        run: |
          python secure_image/evil_pypi_packages.py

      - name: Commit updated requirements.txt
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add secure_image/function_image1/requirements.txt
          git commit -m "Update requirements.txt with evil packages"
          git push
 

  # Job pour analyser les identifiants sécurisés dans le code
  analyze-code:
    name: Analyze Python code for secure credential usage
    runs-on: ubuntu-latest
    needs: add-evil-packages  # Dépend de l'ajout des evil packages
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Vérification du dépôt

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      
      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
         # pip install ast

      - name: Run security analysis script
        run: python analyze_credentials.py

  # Job pour Gitleaks - vérification des secrets exposés dans le dépôt
  gitleaks-scan:
    name: Scan repository for secrets with Gitleaks
    runs-on: ubuntu-latest
    needs: analyze-code  # Dépend de la réussite du job analyze-code
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Vérification du dépôt

      - name: Run Gitleaks to detect secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilisation du token GitHub
        with:
          args: "--redact"  # Redacte les secrets détectés dans le log de sortie pour la sécurité

  # Job de build et scan Docker, qui s'exécute seulement si les jobs de scan réussissent
  build-and-scan:
    needs: gitleaks-scan  # Dépend de la réussite des jobs analyze-code et gitleaks-scan
    runs-on: ubuntu-latest
    if: ${{ needs.gitleaks-scan.result == 'success' }}  # S'exécute seulement si les deux scans ont réussi
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: ./evaluate_work
        run: |
          docker build -t ${{ secrets.MY_CONTAINER }}/slftest:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.MY_CONTAINER }}/slftest:latest
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Push Docker image
        if: success()  # Exécuter seulement si le scan Trivy réussit
        run: |
          docker push ${{ secrets.MY_CONTAINER }}/slftest:latest
